[package]
name = "crosspack-security"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
sha2.workspace = true
