[package]
name = "crosspack-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
semver.workspace = true
serde.workspace = true
toml.workspace = true
