[package]
name = "crosspack-resolver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
crosspack-core = { path = "../crosspack-core" }
semver.workspace = true
